In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [4]:
## Load the Dataset

data = pd.read_csv("Churn_Modelling.csv")

In [5]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [6]:
## Preprocess the data
## Drop irrelevant feature

data = data.drop(columns = ['RowNumber', 'CustomerId', 'Surname'])

In [7]:
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [8]:
## Encode categorical varibale

label_encoder_gender = LabelEncoder()

In [9]:
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [10]:
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [11]:
data['Gender'].value_counts()

Gender
1    5457
0    4543
Name: count, dtype: int64

In [12]:
data['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [13]:
## Onehot encode 'Geography'

from sklearn.preprocessing import OneHotEncoder

In [14]:
onehot_encoder_geo = OneHotEncoder(sparse_output = False)
geo_enoder = onehot_encoder_geo.fit_transform(data[['Geography']])

In [15]:
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [16]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [17]:
geo_encoded_df  = pd.DataFrame(geo_enoder, columns = onehot_encoder_geo.get_feature_names_out(['Geography']))

In [18]:
geo_encoded_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [19]:
## Combine one hot encoder columns with the original data

data = pd.concat([data.drop("Geography", axis = 1), geo_encoded_df], axis = 1)

In [20]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [21]:
## Save the encoders and sclaer


with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)
    print(f"{file} saved sucessfully.!")

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)
    print(f"{file} saved sucessfully.!")

<_io.BufferedWriter name='label_encoder_gender.pkl'> saved sucessfully.!
<_io.BufferedWriter name='onehot_encoder_geo.pkl'> saved sucessfully.!

In [22]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [23]:
## Divide the dataset into independent and dependent features

X = data.drop('Exited', axis = 1)
y = data['Exited']

In [24]:
X.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0.0,0.0,1.0

In [25]:
y.value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [26]:
## Split the data into train and test

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =0.2, random_state = 42)

In [27]:
scaler = StandardScaler()

In [30]:
## Scale the feature

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [31]:
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)
    print(f"{file} saved sucessfully.!")

<_io.BufferedWriter name='scaler.pkl'> saved sucessfully.!

## **ANN Implementation**

In [33]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [35]:
(X_train.shape[1],)

(12,)

In [36]:
## Buid ANN Model

## Input Layer (12) ----> HL1 (64) ----> HL2 (32) ----> Output layer (1)

model = Sequential([
    Dense(64, activation = 'relu', input_shape = (X_train.shape[1],)),    ## HL1 Connected with input layer
    Dense(32, activation = 'relu'),  ## HL2
    Dense(1, activation = 'sigmoid')    ## Output Layer
])

WARNING:tensorflow:From d:\Customer Churn Prediction\venv\lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [38]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
opt = tf.keras.optimizers.Adam(learning_rate = 0.01)
loss = tf.keras.losses.BinaryCrossentropy()

In [ ]:
## Compile the model

# model.compile(optimizer = "adam", loss = 'binary_crossentropy', metrics = ['accuracy'])
model.compile(optimizer = opt, loss = 'binary_crossentropy', metrics = ['accuracy'])

In [61]:
## Setup the TensorBoard

log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

In [62]:
tensorflow_callback = TensorBoard(log_dir = log_dir, histogram_freq = 1)

In [63]:
## Setup Early Stopping

early_stopping_callback = EarlyStopping(monitor = "val_loss", patience = 10, restore_best_weights = True)

In [64]:
## Training the model

history = model.fit(
    X_train, y_train, validation_data = (X_test, y_test), epochs = 100,
    callbacks = [tensorflow_callback, early_stopping_callback]
)

Epoch 1/100
250/250 [==============================] - 3s 11ms/step - loss: 0.3354 - accuracy: 0.8631 - val_loss: 0.3448 - val_accuracy: 0.8595
Epoch 2/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3331 - accuracy: 0.8643 - val_loss: 0.3707 - val_accuracy: 0.8485
Epoch 3/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3317 - accuracy: 0.8637 - val_loss: 0.3483 - val_accuracy: 0.8610
Epoch 4/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3294 - accuracy: 0.8614 - val_loss: 0.3504 - val_accuracy: 0.8525
Epoch 5/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3248 - accuracy: 0.8683 - val_loss: 0.3514 - val_accuracy: 0.8585
Epoch 6/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3268 - accuracy: 0.8630 - val_loss: 0.3489 - val_accuracy: 0.8570
Epoch 7/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3217 - accuracy: 0.8636 - val_loss: 0.3493 - val_accuracy: 0.8540
Epoch 8/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3222 - accuracy: 0.8679 - val_loss: 0.3450 - val_accuracy: 0.8600
Epoch 9/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3157 - accuracy: 0.8695 - val_loss: 0.3658 - val_accuracy: 0.8525
Epoch 10/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3166 - accuracy: 0.8685 - val_loss: 0.3493 - val_accuracy: 0.8560
Epoch 11/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3133 - accuracy: 0.8702 - val_loss: 0.3630 - val_accuracy: 0.8565

In [65]:
model.save('model.h5')

d:\Customer Churn Prediction\venv\lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [66]:
## Load tensorboard Extension

%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [69]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 19216), started 0:11:04 ago. (Use '!kill 19216' to kill it.)