In [47]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [48]:
## Load the trained model, scaler pickle, onehot 

model = load_model("model.h5")

## Load the encoder and scaler

with open('label_encoder_gender.pkl', 'rb') as file:
    label_gender = pickle.load(file)

with open('onehot_encoder_geo.pkl', 'rb') as file:
    label_geo = pickle.load(file)

with open('scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)

In [49]:
## Example Input

input_data = {
    "CreditScore" : 600,
    "Geography" : "France",
    "Gender" : "Male",
    "Age" : 40,
    "Tenure" : 3,
    "Balance" : 60000,
    "NumOfProducts" : 2,
    "HasCrCard" : 1,
    "IsActiveMember" : 1,
    "EstimatedSalary" : 50000
}

In [50]:
geo_encoded = label_geo.transform(
    [[input_data["Geography"]]]
)

# Convert encoded values into DataFrame
geo_encoded_df = pd.DataFrame(
    geo_encoded,
    columns = label_geo.get_feature_names_out(['Geography'])
)

d:\Customer Churn Prediction\venv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [51]:
geo_encoded_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [52]:
# geo_encoded = label_geo.transform([[input_data["Geography"]]]).toarray()
# geo_encoded_df = pd.DataFrame(geo_encoded, columns = label_geo.get_feature_names_out(['Geography']))

In [53]:
input_data = pd.DataFrame([input_data])

In [54]:
input_data

   CreditScore Geography Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France   Male  ...          1               1            50000

[1 rows x 10 columns]

In [55]:
## Encode gender

input_data['Gender'] = label_gender.transform(input_data['Gender'])

In [56]:
input_data.head()

   CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France       1  ...          1               1            50000

[1 rows x 10 columns]

In [57]:
## Combine one-hot encoded columns with input data

input_data = pd.concat([input_data.drop("Geography", axis = 1), geo_encoded_df], axis = 1)

In [58]:
input_data

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          600       1  ...                0.0              0.0

[1 rows x 12 columns]

In [59]:
## Scaline the input

input_scaled = scaler.transform(input_data)

d:\Customer Churn Prediction\venv\lib\site-packages\sklearn\utils\validation.py:2742: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(

In [60]:
input_scaled

array([[6.00000000e+02, 1.00000000e+00, 4.00000000e+01, 3.00000000e+00,
        6.00000000e+04, 2.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        5.00000000e+04, 1.00000000e+00, 4.26325641e-17, 7.19424520e-17]])

In [61]:
## Predict churn

my_prediction = model.predict(input_scaled)

1/1 [==============================] - 0s 184ms/step

In [62]:
my_prediction

array([[1.]], dtype=float32)

In [63]:
prediction_prob = my_prediction[0][0]

In [64]:
prediction_prob

1.0